sudo: required
dist: xenial
services:
  - xvfb
addons:
  chrome: stable

language: node_js
node_js:
  - '12'
  - '10'
cache:
  directories: node_modules

before_script:
  - npm install -g coveralls
  - npm install -g codecov

script:
  - npm run lint
  - npm run flow
  - npm run test:coverage
  - cat coverage/lcov.info | coveralls
  - codecov
  - npm run build
