sudo: required
dist: xenial
services:
  - xvfb
addons:
  chrome: stable

language: node_js
node_js:
  - "10"
  - "8"
cache:
  directories: node_modules

before_script:
  - npm rebuild node-sass

script:
  - npm run lint
  - npm run flow
  - npm run test:coverage
  - npm run build
